version: '3'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www
    depends_on:
      - database
    volumes:
      - ./:/var/www
      - ./.env.dev:/var/www/.env
    links:
      - database

  # The Web Server
  web:
    image: nginx:1.10
    working_dir: /var/www
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - 8080:80

  # The Database
  database:
    image: mysql:5.7.22
    restart: always
    volumes:
        - dbdata:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: developer
      MYSQL_PASSWORD: password

  redis:
    image: redis:4.0-alpine
    ports:
    - 16379:6379
    volumes:
    - redis:/var/lib/redis

volumes:
  dbdata:
  redis:
